### PR TITLE
Fixes for use with Foundation and mocha-jsdom

### PR DESCRIPTION
**Pull request by rm-rf-etc**
We at Lucky Group use mocha-jsdom for unit testing of browser scripts, and Foundation, and these changes allowed us to fix incompatibilities that came up recently between the two. Feel free to respond with feedback and I'll apply any needed updates. Thanks.

### CODE REVIEW

**Comment by rstacruz** [comment]
Why is `window` available in your case?

**Comment by rstacruz** [comment]
I think the `window` check should be on by default. It would be more reasonable to opt into that functionality with an option:

```js
mochaJsdom({ skipWindowCheck: true })
```

```js
if (options.skipWindowCheck && global.window)
  throw new Error(...)
```

**Comment by rstacruz** [comment]
v0.4.0 is out with the `skipWindowCheck` option. cheers. :)

https://github.com/rstacruz/mocha-jsdom/blob/master/HISTORY.md

**Comment by rm-rf-etc** [comment]
Ya, window check is a better solution.

We need `global.window = global` because Foundation defines `window.Foundation`, after which it references Foundation as a global. If global.window does not equal global, then this reference doesn't work. We also can't do this assignment after requiring mocha-jsdom because then the window object it created gets wiped out.

**Pull request closed without merging**
