### PR TITLE
Add useBeforeEach option to specify how it hooks into mocha

### PR DESCRIPTION
**Pull request by jasco**
After adding this I noticed that the functionality was just requested in rstacruz/mocha-jsdom issue #5.

### CODE REVIEW

**Comment by jasco** [comment]
Hold on this for a moment.  Added tests and observed that dom is not resetting between tests.

**Comment by jasco** [comment]
Hold cleared.  The feature passed the test.  I mistyped the option name in my test.

**Comment by rstacruz** [comment]
Nice. have you also thought of other names for the option? `useEach` might be useful, since it's actually using beforeEach and afterEach (where "useBeforeEach" only implies one).

**Comment by rstacruz** [comment]
I'm renaming it to `useEach` and releasing this as 0.4.0. Cheers!

**Comment by dcousens** [comment]
Thanks for the PR @jasco,  I didn't have time to do this myself (at the time).

@rstacruz any reason to not just make this the default?  I can't see any valid reason that `before` would be useful compared to `beforeEach`,  at least, no reason that wouldn't break typical unit testing idioms.

**Comment by rstacruz** [comment]
`before` is much faster :)

**Comment by rstacruz** [comment]
I think it's more reasonable to initialize the DOM just once for the entire Mocha session.

If you're to use Mocha in the context of a browser, the DOM is available to you from the start. You can't "reset" the DOM environment in the browser.

Having your tests perform in a similar environment in the browser and in the console can lead you to test code that can be ran on both the browser and the console. Eg:

- https://github.com/rstacruz/nprogress/blob/master/test/test.js
- In the browser: http://rawgit.com/rstacruz/nprogress/master/test/index.html
- In the console: http://travis-ci.org/rstacruz/nprogress

**Comment by dcousens** [comment]
> You can't "reset" the DOM environment in the browser.

That is a good point,  and although I'd typically opt for ideological unit testing, I think the practicalities of consistent browser and node unit testing is a valid point.

**Pull request merged**
