### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by anselmbradford**
Ignores system generated file.

### CODE REVIEW

**Comment by anselmbradford** [comment]
Looks like there's an issue in istanbul coverage call.

**Comment by rstacruz** [comment]
Ah yes, travis is a little broken at the moment. Might I suggest a global ignore for OS system files instead? :-)

**Comment by anselmbradford** [comment]
The global ignore is cool, but since you have an existing gitignore file I don't see why including more entries is a problem? This means any contributor on a Mac needs a global gitignore set up or they're going to get a `.DS_Store` file in their local repo. My preference would not be to depend or force global environment configuration to keep the repo self-contained, but if that's how you want it, I'd suggest adding a `CONTRIBUTING.md` with instructions.

**Comment by rstacruz** [comment]
If we're to add OS- and editor-based settings, adding a `.DS_Store` (osx) and `*.swp` (vim) would cover my setup—but to be all inclusive to account for everyone, then other environments should be added (like `Thumbs.db` for windows, `*.elc` for emacs). That gitignore would look like this:

https://www.gitignore.io/api/windows,osx,linux,emacs,vim

Maintaining a list like that in every project would be wasteful and may even appear as slightly discriminatory to anyone who doesn't use a similar environment. Artifacts created by your own tools should be cleaned up as part of each developer's responsibility.

**Comment by anselmbradford** [comment]
Fair enough. I'd kind of think the gitignore would organically grow as contributors from different platforms showed up, but I can appreciate desiring to keep it clean, and it looks like the global gitignore is the guidance given in https://git-scm.com/docs/gitignore. I still think `CONTRIBUTING.md` would be a good spot to evangelize that! ;-D

**Pull request closed without merging**
