### PR TITLE
Update JSDOM

### PR DESCRIPTION
**Pull request by RobLoach**
Follows https://github.com/rstacruz/mocha-jsdom/pull/28 and #18 in an attempt make the Travis tests pass.

Since we are now requiring JSDOM >10.0.0, we may need to bump the major version up.

### CODE REVIEW

**Comment by jissereitsma** [comment]
I can confirm that this PR works. Could this be merged?

**Comment by cgarnier** [comment]
Just add the right version of JSDOM in dependencies

**Comment by jissereitsma** [comment]
Unfortunately, this does not work for me, because it means all other dependencies that rely on JSDOM also need to be downgraded. For now, I've solved my own issue by simply using plain JSDOM code to give me what I needed. But I think that if you look at all 3 scenarios - removing `mocha-jsdom`, downgrading `jsdom` for working around this, or merging the PR - only the PR brings this project forward.

**Comment by cgarnier** [comment]
I said that mocha-jsdom should have the right version of jsdom in its package.json. It should nt be a unmet dep.

**Comment by jissereitsma** [comment]
Ah, sorry, my mistake. But the current `package.json` of mocha-jsdom mentions the following: `"jsdom": "7.0.2",`. Isn't that what you mentioned?

**Comment by cgarnier** [comment]
It mentioned as a dev dep and as peers dep. It should be removed from this two place and moved to the dependenties section. That way, the jsdom@7 should be correcly installed.

**Comment by jissereitsma** [comment]
Ah, I learned something today - thanks!

**Comment by diego-codes** [comment]
Hi there! Is there a plan to merge this fix in the near future?

**Comment by jshor** [comment]
:+1:

**Comment by fernandohenriques** [comment]
Hello @rstacruz, do not forget this merge...

**Comment by rstacruz** [comment]
Oops! Let me attend to this in a bit. For some reason I didn't see this in my notifications. Thanks for bringing it to my attention :)

**Comment by rstacruz** [comment]
Merged! I'll also do some more updates #31. I'll push a 1.x-compatible version (v1.2.0), and a new version (v2.0.0) which includes jsdom as a direct dependency.

**Pull request merged**
